var GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';
var GITHUB_USER = process.env.GITHUB_USERNAME || '';

function ghHeaders() {
  return { 'Authorization': 'token ' + GITHUB_TOKEN, 'Content-Type': 'application/json', 'Accept': 'application/vnd.github.v3+json' };
}

function toBase64(str) { return Buffer.from(str, 'utf-8').toString('base64'); }

export async function createRepo(repoName, files) {
  var createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST', headers: ghHeaders(),
    body: JSON.stringify({ name: repoName, private: false, auto_init: true, description: 'Generated by Kumo AI' }),
  });
  if (!createRes.ok) {
    var err = await createRes.json();
    var isExisting = err.errors && err.errors[0] && err.errors[0].message === 'name already exists on this account';
    if (!isExisting) throw new Error('GitHub: ' + JSON.stringify(err));
  }

  for (var attempt = 0; attempt < 15; attempt++) {
    await new Promise(function(r) { setTimeout(r, 1500); });
    var check = await fetch('https://api.github.com/repos/' + GITHUB_USER + '/' + repoName + '/contents/', { headers: ghHeaders() });
    if (check.ok) break;
  }

  var entries = Object.entries(files);
  for (var i = 0; i < entries.length; i++) {
    var filePath = entries[i][0];
    var content = entries[i][1];
    if (typeof content !== 'string') content = JSON.stringify(content, null, 2);
    var putBody = { message: 'Add ' + filePath, content: toBase64(content), branch: 'main' };
    var existRes = await fetch('https://api.github.com/repos/' + GITHUB_USER + '/' + repoName + '/contents/' + filePath, { headers: ghHeaders() });
    if (existRes.ok) { putBody.sha = (await existRes.json()).sha; }
    var putRes = await fetch('https://api.github.com/repos/' + GITHUB_USER + '/' + repoName + '/contents/' + filePath, {
      method: 'PUT', headers: ghHeaders(), body: JSON.stringify(putBody),
    });
    if (!putRes.ok) { var putErr = await putRes.text(); throw new Error('GitHub upload failed for ' + filePath + ': ' + putErr); }
  }

  var giBody = { message: 'Add .gitignore', content: toBase64('node_modules\n.next\n.env\n.env.local\n'), branch: 'main' };
  var giCheck = await fetch('https://api.github.com/repos/' + GITHUB_USER + '/' + repoName + '/contents/.gitignore', { headers: ghHeaders() });
  if (giCheck.ok) { giBody.sha = (await giCheck.json()).sha; }
  await fetch('https://api.github.com/repos/' + GITHUB_USER + '/' + repoName + '/contents/.gitignore', { method: 'PUT', headers: ghHeaders(), body: JSON.stringify(giBody) });

  return 'https://github.com/' + GITHUB_USER + '/' + repoName;
}
